services:
  db:
    image: docker.io/library/postgres:16-alpine
    environment:
      POSTGRES_DB: candour
      POSTGRES_USER: candour
      POSTGRES_PASSWORD: candour_dev_password
    ports:
      - "5432:5432"
    volumes:
      - candour-dev-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U candour"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  candour-dev-data:
